### Create a new Student
POST http://localhost:8080/v1/students
Content-Type: application/json

{
  "studentId" : 123456,
  "firstName" : "Peter",
  "lastName" : "Pan"
}

### Get Student By studentId
GET http://localhost:8080/v1/students/123456

### Update an existing Student
PATCH http://localhost:8080/v1/students
Content-Type: application/json

{
  "studentId" : 1234,
  "firstName" : "Peter",
  "lastName" : "Panhandler"
}

### Delete Student By studentId
DELETE http://localhost:8080/v1/students/99