spring:
  datasource:
    url: jdbc:h2:file:~/testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    #properties:
     # javax:
      #  persistence:
       #   schema-generation:
        #    scripts:
         #     action: create
          #    create-target: schema.sql
           #   create-source: metadata
  h2:
    console:
      path: /h2
      enabled: true